---
apiVersion: v1
kind: Service
metadata:
  name: restapi-service
spec:
  selector:
    app: restapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi-deployment
  labels:
    app: restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: restapi
          image: docker.io/library/restapi:local 
          ports:
            - containerPort: 80
          env:
            - name: db_name
              value: sql
