---
apiVersion: v1
kind: Service
metadata:
  name: restapi
spec:
  selector:
    app: restapi
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 32576
    port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
  labels:
    app: restapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      containers:
        - name: restapi
          image: thecuriousdoggo/restapi:public 
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: db_name
              value: sql
